# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mistletoe < Formula
  desc "Mistletoe CLI tool"
  homepage "https://github.com/keiji/mistletoe"
  version "0.1.0-rc2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc2/mistletoe_0.1.0-rc2_darwin_amd64.tar.gz"
      sha256 "b8cb7ccdcb2addad3f69acabbef6eab8887afd544fe09bc7055c00dfe1314593"

      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc2/mistletoe_0.1.0-rc2_darwin_arm64.tar.gz"
      sha256 "0989bb9bfcb6c93b96d0b5657ff019f4182d914810c314421c2b8a78acf54bc4"

      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc2/mistletoe_0.1.0-rc2_linux_amd64.tar.gz"
      sha256 "32ae41af9ab9bb2b04eaccc1e24f5d2c6652c4b61a0d716e8d534dea0e650bae"
      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc2/mistletoe_0.1.0-rc2_linux_arm64.tar.gz"
      sha256 "7e88597f60a1ef866da27867393607d4258eb133fb00d2052026ae2e24e63bd5"
      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
  end
end
