# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mistletoe < Formula
  desc "Mistletoe CLI tool"
  homepage "https://github.com/keiji/mistletoe"
  version "0.1.0-rc5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc5/mistletoe_0.1.0-rc5_darwin_amd64.tar.gz"
      sha256 "db4c89f8ee9ef52d30339e9786ce9c30ec9807c42b1a555f239b968071104f9e"

      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc5/mistletoe_0.1.0-rc5_darwin_arm64.tar.gz"
      sha256 "43eb7b0736aca618f1bcf7a3eee7b69475da18e149b5693c1a5f9e651132ab64"

      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc5/mistletoe_0.1.0-rc5_linux_amd64.tar.gz"
      sha256 "421cb9498a522f05d85bd8f5213c0aa50b6717c75b4cda0269ab0a07ef8d16e7"
      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0-rc5/mistletoe_0.1.0-rc5_linux_arm64.tar.gz"
      sha256 "901d2e78abc503f5d9fda724eb8c9d9ad323f49e0adab80b607d2144980e0eca"
      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
  end
end
