# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mistletoe < Formula
  desc "Mistletoe CLI tool"
  homepage "https://github.com/keiji/mistletoe"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0/mistletoe_0.1.0_darwin_amd64.tar.gz"
      sha256 "89cc5a0e5cf6a70d44457d7eeb3c82cd8b1c36e0095835d9ed8f48167d558428"

      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0/mistletoe_0.1.0_darwin_arm64.tar.gz"
      sha256 "f0b5b75c892f34317433649c3b18e18260a39e8db81daed14ca40beded692a6a"

      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0/mistletoe_0.1.0_linux_amd64.tar.gz"
      sha256 "94e7365ad5ea9865ba1c29cc314b2609bcf4760f1be060c9b39cab82b0bd9188"
      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keiji/mistletoe/releases/download/v0.1.0/mistletoe_0.1.0_linux_arm64.tar.gz"
      sha256 "180e7cd551a6b5fae5cba455d8520cad07400760cc1a21719117b600d9490fe7"
      def install
        bin.install "mstl"
        bin.install "mstl-gh"
      end
    end
  end
end
