# This file was generated by GoReleaser. DO NOT EDIT.
cask "mistletoe" do
  name "mistletoe"
  desc "Mistletoe CLI tool"
  homepage "https://github.com/keiji/mistletoe"
  version "0.1.0-rc1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mstl"
  binary "mstl-gh"

  on_macos do
    on_intel do
      url "https://github.com/keiji/mistletoe/releases/download/v#{version}/mistletoe_#{version}_darwin_amd64.tar.gz"
      sha256 "619a02fa8d193030ccfddb14d5bca2ab79b300763f96efb694e9f32cc83d827f"
    end
    on_arm do
      url "https://github.com/keiji/mistletoe/releases/download/v#{version}/mistletoe_#{version}_darwin_arm64.tar.gz"
      sha256 "8e1af643fe7205601913348a9c3e5ee910d5ee1a26c75cc29b385f6d43c3cfc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/keiji/mistletoe/releases/download/v#{version}/mistletoe_#{version}_linux_amd64.tar.gz"
      sha256 "76c870dc750f1bce0e88e4f5ac20264a258977aa13dba7ba45820c0cf87c1706"
    end
    on_arm do
      url "https://github.com/keiji/mistletoe/releases/download/v#{version}/mistletoe_#{version}_linux_arm64.tar.gz"
      sha256 "1fbf9b1596ad0edc76684568484e35c3eb7dfddf45865a82153d6e14823991f7"
    end
  end

  # No zap stanza required
end
